spring.config.import=optional:classpath:.env
# JDBC
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=/Users/daniakuspanova/IdeaProjects/employment-calendar/src/main/resources/keystore/demo.p12
server.ssl.key-store-password=${CERTIFICATE_KEY_PASSWORD}
server.ssl.key-alias=demo-alias
